import discord


# To render a button OR a GROUP of buttons we need to write a class to handle that specific situation
class View(discord.ui.View):
    # This line creates the button which is generated by the function on_button_click() which is defined below it.
    # All buttons need to have a function attached or else this line alone will be highlighted squiggly/incorrect syntax
    @discord.ui.button(label="Click Me", style=discord.ButtonStyle.success, emoji="✅")

    # You MUST pass: self, button, and interaction. 
    async def on_success_click(self, button, interaction):
        # Here is where you can determine how the bot responds 
        await button.response.send_message(f"Button was clicked.")
    

    # To render more than one button you literally just copy and paste the same structure and edit as need:

    @discord.ui.button(label="Click Me", style=discord.ButtonStyle.danger, emoji="❌")
    async def on_failure_click(self, button, interaction):
        await button.response.send_message(f"Button was clicked.")

    @discord.ui.button(label="Click Me", style=discord.ButtonStyle.primary, emoji="⚙️")
    async def on_premium_click(self, button, interaction):
        await button.response.send_message(f"Button was clicked.")



# associated commands:
def testCreateButtonEmbed():
    button_embed = discord.Embed(
        title="Placeholder Embed",
        description="This is a placeholder embed. Click this button!"
    )

    return button_embed, View()

